### ISSUE TITLE
【自治体標準オープンデータセット】ジオコーディング

### ISSUE THREAD

**Issue by yamamoto-ryuzo** [dx-junkyard/OpenData-Bridge-DataNorm#18]
こちらでジオコーディングに関する打ち合わせが出来ればと思います。

https://www.digital.go.jp/policies/data_strategy_government_interoperability_framework/
にも
![image](https://github.com/dx-junkyard/OpenData-Bridge-DataNorm/assets/86514652/d4ab1794-179b-4adb-9538-b4254a212c16)
でアドレスベースレジストリを使えと書いてますので。
それに準じたCSVからのジオコーディングが良いと思われます。

アドレスベースレジストリの詳細はこちらから
https://www.digital.go.jp/policies/base_registry_address

【住居データの整備について】
 **今回はこちらのみ実施！** 
 目黒区　https://drive.google.com/drive/folders/1Ap3LdjcRhbvniyGIc43rLsK-OuiomXoD
 北九州　https://drive.google.com/drive/folders/1UZZhHvuGBqIK8Ahlqee0eq3B4LJW6O7S

【番地データの整備について】・・・こちらは整備保留！
北九州を例に法務局からの公開データ属性は
https://drive.google.com/file/d/1Y4Ap3UUP72Z5xA2N_mzKC--NALKJaeTr/view?usp=drive_link
の感じがいいと思います。
座標は番地の重心座標です。

**Comment by yamamoto-ryuzo** [comment]
あ！GIFにご作法が乗ってました・・・
内容は、また、確認しようと思いますが、忘れたらいけないので投げておきます。

https://github.com/JDA-DM/GIF/blob/main/430_%E3%82%B3%E3%82%A2%E3%83%87%E3%83%BC%E3%82%BF%E3%83%A2%E3%83%87%E3%83%AB/docx/433_%E3%82%B3%E3%82%A2%E3%83%87%E3%83%BC%E3%82%BF%E3%83%A2%E3%83%87%E3%83%AB%E8%A7%A3%E8%AA%AC%E6%9B%B8_%E4%BD%8F%E6%89%80.docx

**Comment by yamamoto-ryuzo** [comment]
本日よりGIF対応版？ジオコーディングの属性定義を整理開始しました。

https://docs.google.com/spreadsheets/d/1l8S14Xgz-KPD3W_BZucWMadeJINk1vSx/edit?usp=drive_link&ouid=110098866251138022891&rtpof=true&sd=true

**Comment by Mitsuo-Koikawa** [comment]
ジオコーディングのデータそのものではなく、それを作成した過程を共有していただく事は可能でしょうか？位置座標データ作成過程をシステム化できればと思います。

**Comment by fukumoto19981020** [comment]
azure mapsを使ってジオコーディング結果
日本だと市区町村レベルまでしか入力できないみたい（https://learn.microsoft.com/ja-jp/azure/azure-maps/geocoding-coverage#asia-pacific）

入力1:日本東京千代田市
出力1:{'summary': {'query': '日 本 东 京 千 代 田 市', 'queryType': 'NON_NEAR', 'queryTime': 60, 'numResults': 1, 'offset': 0, 'totalResults': 1, 'fuzzyLevel': 2}, 'results': [{'type': 'Geography', 'id': 'ct4l5cvfxjS5r5lWQsVTkA', 'score': 8.2069892883, 'entityType': 'MunicipalitySubdivision', 'matchConfidence': {'score': 0.29142195913622027}, 'address': {'municipalitySubdivision': '千葉', 'municipality': '東京', 'countrySubdivision': 'Kanto', 'countrySubdivisionName': 'Kanto', 'countryCode': 'JP', 'country': '日本', 'countryCodeISO3': 'JPN', 'freeformAddress': '東京 千葉, Kanto'}, 'position': {'lat': 35.58038, 'lon': 140.11346}, 'viewport': {'topLeftPoint': {'lat': 35.64492, 'lon': 140.07999}, 'btmRightPoint': {'lat': 35.56562, 'lon': 140.14694}}, 'boundingBox': {'topLeftPoint': {'lat': 35.64492, 'lon': 140.07999}, 'btmRightPoint': {'lat': 35.56562, 'lon': 140.14694}}, 'dataSources': {'geometry': {'id': '00004153-3200-3c00-0000-000065a03f04'}}}]}

入力2:日本東京都千代田区丸の内一丁目
出力2:{'summary': {'query': '日 本 东 京 都 千 代 田 区 丸 の 内 一 丁 目', 'queryType': 'NON_NEAR', 'queryTime': 95, 'numResults': 0, 'offset': 0, 'totalResults': 0, 'fuzzyLevel': 2}, 'results': []}

**Comment by yamamoto-ryuzo** [comment]
国が進めているのは、アドレス・ベースレジストリの整備です。
その範疇内でジオコーディングの場合は、
https://drive.google.com/file/d/1Y4Ap3UUP72Z5xA2N_mzKC--NALKJaeTr/view?usp=drive_link
こんな感じのデータを作るので、そこを検索してもらう感じになると思います。

どうしても、座標を取得したいというのなら有料サービスになるかと思います。
デジ庁案件を考えるのなら、どちらかは、戀川さんに確認してもらう必要があると思います。

明日は、こちらのアドレス・ベースレジストリの情報を充実させようかと思います。
北九州と目黒区を作成予定です。

**Comment by yamamoto-ryuzo** [comment]
目黒区のデータはこちらに整理いします。
住居表示：整備済み（再加工が必要）

https://catalog.registries.digital.go.jp/rc/dataset/
必要なデータセットは
市区町村名 住居表示－住居マスター位置参照拡張 データセット
市区町村名 住居表示－街区マスター位置参照拡張 データセット

目黒区の場合は
https://catalog.registries.digital.go.jp/rc/dataset/?q=%E7%9B%AE%E9%BB%92%E5%8C%BA&sort=score+desc%2C+metadata_modified+desc

[東京都 目黒区 住居表示－住居マスター位置参照拡張 データセット](https://catalog.registries.digital.go.jp/rc/dataset/ba-o1-131105_g2-000008)
【課題】街区までの日本語表示がない
![image](https://github.com/dx-junkyard/OpenData-Bridge-DataNorm/assets/86514652/70b41d5c-7b0b-4129-b121-c81ba4b0b1cd)

【課題】街区までしかデータがないため役に立たない
[東京都 目黒区 住居表示－街区マスター位置参照拡張 データセット](https://catalog.registries.digital.go.jp/rc/dataset/ba-o1-131105_g2-000007)
![image](https://github.com/dx-junkyard/OpenData-Bridge-DataNorm/assets/86514652/80a36236-fc83-431b-859d-bafb5b80d4a5)

【住居データの整備について】
この二つをミックスして利用！できるようにするとこうなる！
目黒区　https://drive.google.com/drive/folders/1Ap3LdjcRhbvniyGIc43rLsK-OuiomXoD

**Comment by yamamoto-ryuzo** [comment]
北九州市のデータはこちらに整理いします。
住居表示：整備済み（再加工が必要）
https://catalog.registries.digital.go.jp/rc/dataset/?q=%E5%8C%97%E4%B9%9D%E5%B7%9E&sort=score+desc%2C+metadata_modified+desc

詳細は[ジオコーディングデータ作成方法（python編）](https://github.com/dx-junkyard/OpenData-Bridge-DataNorm/issues/18#issuecomment-1868246285)参照

【住居データの整備について】
北九州　https://drive.google.com/drive/folders/1UZZhHvuGBqIK8Ahlqee0eq3B4LJW6O7S

目黒区のように全域とはいかないものの、さすが北九州おおむねの人口は網羅出来てるっぽい感じ！？たぶん？？？
![image](https://github.com/dx-junkyard/OpenData-Bridge-DataNorm/assets/86514652/30b498e9-acb5-49cb-bcbd-373695367762)

**Comment by yamamoto-ryuzo** [comment]
![image](https://github.com/dx-junkyard/OpenData-Bridge-DataNorm/assets/86514652/4a6740f0-b300-4d27-8c96-7526b64da344)

【番地データの整備について】
とりあえずベースレジストリとしては未整備となっており、今回は我々も未整備で処理でいいですかね～～～
逆に、自治体がデータ持ってる場合は、その時に対応ということで！
課税の関係で整備している自治体も多いでしょうから。
![image](https://github.com/dx-junkyard/OpenData-Bridge-DataNorm/assets/86514652/dc2508a3-2d5e-4254-82a1-07f44054bd1d)
アドレス・ベース・レジストリ データ解説書 <2022年4月 試験公開版> 抜粋

**Comment by yamamoto-ryuzo** [comment]
デジタル庁のアドレスベースレジストリとジオコーディングに対する考えについて

どうも、下記の通り入札が行われ、別途検証が行われているようです。たぶん？？？タイトルからして。。
我々が、これ以上時間かけてもたぶん、別途検証と重複するだけなので、今回は、上の案、程度で検索にかからなかったものは「ＮＵＬＬ」でよいかと思います。

https://www2.njss.info/offers/view/27132132
↑　無料では閲覧に回数制限あります。

**Comment by yamamoto-ryuzo** [comment]
ジオコーディングデータ作成方法
居住マスタと街区マスタをリレーションしてあげるだけ・・・
リレーションが得意なのはリレーショナルデータベース、なので、今回はデータベース機能も有しているQGISで作成の例を明示

#### 1.CSVデータの読み込み

今回読み込むデータはこの2つ
![image](https://github.com/dx-junkyard/OpenData-Bridge-DataNorm/assets/86514652/bcadb78a-9e9f-4482-8611-69e537345bee)
下記操作を２つのファイルで実施
![image](https://github.com/dx-junkyard/OpenData-Bridge-DataNorm/assets/86514652/a697d19b-90ce-40dc-95ff-ce678001eb1c)
![image](https://github.com/dx-junkyard/OpenData-Bridge-DataNorm/assets/86514652/ff4c1a89-6f09-44f3-ae27-666a37ac5e00)
#### 2.CSVデータのリレーション（結合）
フィールド計算機で「町字+街区」のIDを２つのファイルで作成
![image](https://github.com/dx-junkyard/OpenData-Bridge-DataNorm/assets/86514652/8509632e-0300-44b7-a09f-4961eb627214)
「町字+街区」のIDをキーに結合
![image](https://github.com/dx-junkyard/OpenData-Bridge-DataNorm/assets/86514652/c29730f8-9901-4b2c-84ab-9045a634a59b)
#### 3.データの確認
![image](https://github.com/dx-junkyard/OpenData-Bridge-DataNorm/assets/86514652/e8fba680-d22e-406d-91bc-020bc70f9d27)
![image](https://github.com/dx-junkyard/OpenData-Bridge-DataNorm/assets/86514652/f63209bb-2618-4dc8-af85-2bd41e1bfa7a)
雰囲気あっているっぽい！
#### 4.データのエクスポート
![image](https://github.com/dx-junkyard/OpenData-Bridge-DataNorm/assets/86514652/aaf38d35-2977-49b3-89bb-842e4eb8e70b)
今回はあえてEPSGコードの変更は行わなず、元のデータを尊重する。
参考までに現在はJDG2011、整備データはJGD2000と古い。
![image](https://github.com/dx-junkyard/OpenData-Bridge-DataNorm/assets/86514652/668ab6ef-814b-47e7-bf99-301586b46b39)
#### 5.CSVデータの確認
期待通り！
![image](https://github.com/dx-junkyard/OpenData-Bridge-DataNorm/assets/86514652/57e522b2-b13c-4fc8-9615-94007648302e)

**Comment by yamamoto-ryuzo** [comment]
ジオコーディングデータ作成方法（ChatGPT4を主に使う編）  

　結局、Pythonで書いた方が早かったので中止！
　中止理由は、データ収集とかしてくれなかった・・・残念。

1. CSVデータの収集  
収集対象ファイルは以下の2サイト  
（住居マスター）  
https://catalog.registries.digital.go.jp/rc/dataset/?q=北九州市&06_rc_type=住居表示－住居マスター位置参照拡張（市区町村）&sort=score+desc%2C+metadata_modified+desc  
（街区マスター）  
https://catalog.registries.digital.go.jp/rc/dataset/?q=北九州市&06_rc_type=住居表示－街区マスター位置参照拡張（市区町村）&sort=score+desc%2C+metadata_modified+desc  

1. データファイルの結合

1. CSVデータのリレーション（結合）  

1. データの確認

**Comment by yamamoto-ryuzo** [comment]
ジオコーディングデータ作成方法（python編）

コード等はこちら
https://drive.google.com/drive/folders/1UZZhHvuGBqIK8Ahlqee0eq3B4LJW6O7S

ver2023-12-23　とりあえずファイル一覧からファイルをダウンロードして一つのファイルにまとめるところまで
ver2023-12-24　とりあえず完成のは

![image](https://github.com/dx-junkyard/OpenData-Bridge-DataNorm/assets/86514652/4c263521-2000-4e66-8d60-68e6d524c524)


```python
##########################
######## 使いかた #########
##########################
### 入力
#市区町村名 住居表示－街区マスター位置参照拡張 データセット
#"gaiku_url_list.txt　にURLを入力
#市区町村名 住居表示－住居マスター位置参照拡張 データセット
#"jyuukyo_url_list.txt"にURLを入力
###　出力
# 二つのデータセットを統合し、住居データとして出力
#'merged_jyuukyo.csv' ファイルが出力されます
# workフォルダには作業の状況が残ります
# ただし、work/extracted_filesフォルダ内は最後に作用した状況のみです

##################################################################
######### モジュール(module)やパッケージ(package)の読み込み #########
##################################################################
#Webページやデータを取得
import requests
#ZIPの圧縮・解凍
import zipfile
#OS依存機能を利用
import os
#データ分析作業を支援するためのモジュール
import pandas as pd
import shutil

###########################
######### 関数定義 #########
###########################
### ファイルのダウンロード
def download_file(url, local_filename):
    # URLからファイルをダウンロードし、特定のローカルファイルパスに保存する
    with requests.get(url, stream=True) as r:
        r.raise_for_status()
        with open(local_filename, 'wb') as f:
            for chunk in r.iter_content(chunk_size=8192):
                f.write(chunk)
    return local_filename
### 住居表示ファイルの取得及び結合
def address_download(file_name,combined_data_file):
    ### work/extracted_files　フォルダのクリーニング
    ### ※注意！　フォルダ内全ての一括処理があるため必ずその都度クリーニングを行うこと
    extracted_folder_path = 'work/extracted_files'
    if os.path.exists(extracted_folder_path):
        shutil.rmtree(extracted_folder_path)
    os.makedirs(extracted_folder_path)
    print(f"work/extracted_filesフォルダのクリーニングが完了しました。")
    ### 指定ファイル内のファイル一覧を読み込む
    # ファイルを読み込みモードで開く
    with open(file_name, "r") as file:
        # ファイルから行を1行ずつ読み込む
        file_list = file.readlines()
    # 各行の末尾の改行文字を削除
    file_list = [line.strip() for line in file_list]
    ### 読み込んだファイル一覧を順次処理
    for file_path in file_list:
        print(file_path)
        ### ファイルのダウンロード
        url = file_path
        local_filename = 'work/download.zip'
        download_file(url, local_filename)
        ### ダウンロードしてZIPファイルを読み込みモードで開き解凍
        with zipfile.ZipFile(local_filename, 'r') as my_zip:
            # ZIPファイル内のファイル一覧を表示
            file_list = my_zip.namelist()
            print("ZIPファイル内のファイル一覧:")
            for file_name in file_list:
                print(file_name)
            # ZIPファイル内の全てのファイルを解凍
            my_zip.extractall('work/extracted_files')
            ### 所定のフォルダ内のすべてのCSVファイルを結合
            ### 最初のファイルの属性行を取得しそれ以降のファイルの属性行は無視
            # CSVファイルが保存されているディレクトリを指定
            csv_directory = 'work/extracted_files'
            # 最初のCSVファイルから列名を取得
            first_file = os.listdir(csv_directory)[0]
            first_file_path = os.path.join(csv_directory, first_file)
            first_df = pd.read_csv(first_file_path)
            column_names = first_df.columns.tolist()
            # 結合するための空のDataFrameを作成
            combined_data = pd.DataFrame(columns=column_names)
            # 指定したディレクトリ内のCSVファイルを結合
            for filename in os.listdir(csv_directory):
                if filename.endswith(".csv"):
                    file_path = os.path.join(csv_directory, filename)
                if file_path == first_file_path:
                    # 最初のファイルはスキップして、列名を引き継ぐ
                    continue
                df = pd.read_csv(file_path)
                # 列名を引き継いで結合
                combined_data = pd.concat([combined_data, df], ignore_index=True)
                # 結合したデータを1つのCSVファイルに保存
                combined_data.to_csv(combined_data_file, index=False)
            print(f"CSVファイルの結合が完了しました。")
    ### CSVファイルを文字列として読み込む
    df = pd.read_csv(combined_data_file,dtype=str)
    # 結合したい文字列の属性を選択し、新しい文字列の属性を作成する
    df['街区ユニークid'] = df['全国地方公共団体コード'] + df['町字id'] + df['街区id']
    # 新しいCSVファイルに保存する
    df.to_csv(combined_data_file, index=False)
    print(f"街区ユニークidを追加しました。")
    return

#########################
######## メイン #########
########################
try:
    ### work　フォルダのクリーニング
    work_folder_path = 'work'
    if os.path.exists(work_folder_path):
        shutil.rmtree(work_folder_path)
    os.makedirs(work_folder_path)
    print(f"workフォルダのクリーニングが完了しました。")
    ### 住居表示ファイルの取得及び結合
    # address_download("住居表示ファイル名一覧ファイル名を指定",'結合住居表示ファイル名')
    #市区町村名 住居表示－街区マスター位置参照拡張 データセット
    address_download("gaiku_url_list.txt",'work/combined_gaiku.csv')
    print(f"市区町村名 住居表示－街区マスターが作成されました。")
    #市区町村名 住居表示－住居マスター位置参照拡張 データセット
    address_download("jyuukyo_url_list.txt",'work/combined_jyuukyo.csv')
    print(f"市区町村名 住居表示－住居マスターが作成されました。")
    ###　住居マスターに街区マスターを結合する
    # 1つ目のCSVファイルを読み込む
    df1 = pd.read_csv('work/combined_jyuukyo.csv')
    # 2つ目のCSVファイルを読み込む
    df2 = pd.read_csv('work/combined_gaiku.csv')
    # 属性をキーにして結合
    # 結合方式はleftのすべての行が保持
    # 同じ属性が重複する場合は街区データ側に接尾辞を追加
    merged_df = pd.merge(df1, df2, on='街区ユニークid', how='left', suffixes=('', '_街区'))
    # 結合結果を新しいCSVファイルとして保存
    merged_df.to_csv('merged_jyuukyo.csv', index=False)
    print(f"居住データベースが作成されました。")
# エラー処理
except FileNotFoundError:
    print(f"ファイルが見つかりません。")
except Exception as e:
    print(f"エラーが発生しました: {e}")
```

**Comment by yamamoto-ryuzo** [comment]
GPT4先生にデータを検索してもらった
https://chat.openai.com/share/45d15d1d-4b89-4150-ac8d-56d1f18197ac
![image](https://github.com/dx-junkyard/OpenData-Bridge-DataNorm/assets/86514652/e1a104b5-514a-4c6c-8e9f-0d1b9d6edafd)
QGISでのデータ表示
![image](https://github.com/dx-junkyard/OpenData-Bridge-DataNorm/assets/86514652/cff25af8-9584-4b85-ba3f-cdeed804d4b0)
小数点が勝手に切られているが、ちゃんと検索してくれていると思われる（たぶん）。
が、すごく遅い。。。実務では使えない。

**Comment by yamamoto-ryuzo** [comment]
https://datanorm.azurewebsites.net/api/geocode?city_block_id=3&residence_id=28&address=赤岩町  

APIにも無事実装されれ多様なので、このスレッドはクローズです。

つづきは
https://github.com/dx-junkyard/OpenData-Bridge-DataNorm/issues/19

![image](https://github.com/dx-junkyard/OpenData-Bridge-DataNorm/assets/86514652/3ad64ab4-5c11-48aa-b625-67190d47d6e7)

**Comment by yamamoto-ryuzo** [comment]
【自治体標準オープンデータセット】補完データ（公共施設）
https://github.com/dx-junkyard/OpenData-Bridge-DataNorm/issues/20
へ続く！
