### ISSUE TITLE
【proxy-api】データベース領域の有無について

### ISSUE THREAD

**Issue by yamamoto-ryuzo** [dx-junkyard/OpenData-Bridge-DataNorm#22]
@fukumoto19981020  

1/6の打ち合わせによると、proxy-api環境は、内部にデータベースを保持できないと言われていましたが。  

class GeocodeRepository(object):
    def __init__(self):
        self.df = pd.read_csv(os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), 'resources', 'geocode', 'merged_jyuukyo.csv'))  
        
によると、内部に　merged_jyuukyo.csv　保持しているような？  
         
![image](https://github.com/dx-junkyard/OpenData-Bridge-DataNorm/assets/86514652/c3c41083-f851-4add-9395-f6b353903648)

**Comment by fukumoto19981020** [comment]
保持しています

**Comment by yamamoto-ryuzo** [comment]
了解です。
