### ISSUE TITLE
【proxy-api】azureについて

### ISSUE THREAD

**Issue by yamamoto-ryuzo** [dx-junkyard/OpenData-Bridge-DataNorm#23]
1.azure前提のシステム
雰囲気
import azure.functions as func
てことは、azure前提のシステムでよかったでしょうか？
ま～～私、azure環境持ち合わせていないので、よく知りませんが。。。💦

![image](https://github.com/dx-junkyard/OpenData-Bridge-DataNorm/assets/86514652/18744ad3-34d2-45d7-8ee7-4e37c67c07ab)

2.azureってモジュールのインストールは自由に出来るってことでよかったでしょうか
python上で　import　したら、勝手にモジュールインストールしてくれるとか？？？

**Comment by fukumoto19981020** [comment]
ローカルでazure functionsの環境を作る必要があります
https://qiita.com/pkopko-b8/items/0083c86af60339435e00

**Comment by yamamoto-ryuzo** [comment]
> ローカルでazure functionsの環境を作る必要があります https://qiita.com/pkopko-b8/items/0083c86af60339435e00

　これは、VSCODE用の開発環境用であって、最終的にはAZUREに行かなくてはいけないという認識なのですが。
　ほかの、AZUREサービスでないOS環境でも動くってことです？？？

**Comment by fukumoto19981020** [comment]
windows, mac, linuxで動くと思いますよ
